version: "3"

services:
  node:
    image: vue_node
    entrypoint: bash
    volumes:
      - "$PWD:/usr/src/app"
    working_dir: /usr/src/app 
    environment: 
      - http_proxy=""
    ports:
      - "8080:8080"