version: "3"

services:
  db:
    build: ./
    image: myimg
    environment:
      - "POSTGRES_PASSWORD=123"
    ports:
      - "5432:5432"
      
  spring:
    image: maven
    entrypoint: mvn spring-boot:run
    working_dir: /usr/src/mymaven
    volumes:
      - "/home/allan/Documentos/projetos/git/dgapp:/usr/src/mymaven"
      - "~/.m2:/root/.m2"
    ports:
      - "8081:8081"
    links:
      - db

  vue:
    image: node
    working_dir: /usr/src/app
    volumes:
      - "/home/allan/Documentos/projetos/git/dgapp-ui:/usr/src/app"
    ports:
      - "8080:8080"
    # environment:
    #   - "http_proxy=http://allan.fernandes:Ee6D22d%40@prxdf.prevnet:3128"
    entrypoint: "npm run dev"
